Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 1. Решение:

In [16]:
import numpy as np 

In [21]:
N=int(input("Введите число, от которого неободимо отсчитать массив по убыванию:  "))
np.arange(N,0,-1)

Введите число, от которого неободимо отсчитать массив по убыванию:  10


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [67]:
matr=np.diag(np.arange(N,0,-1), k=0)
summ_diag=sum(sum(matr))

print(matr)
print(summ_diag)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
55


Если элементы, отличные от нуля стоят на главной дигонали, то 0 не включится. 0 включить можно, если матрицу сделать не квадратной:

In [68]:
matr2=np.diag(np.arange(N,0,-1), k=1)
summ2_diag=sum(sum(matr2))


print(matr2)
print(summ2_diag)

[[ 0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
55


55


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [27]:
import numpy as np

a1=np.array([[4,2,1]])
a2=np.array([[1,3,0]])
a3=np.array([[0,5,4]])
b=np.array([4,12,-3])

In [28]:
matr_coef=np.concatenate((a1,a2,a3),axis=0)

#решение с помощью встроенного в Numpy метода
from numpy import linalg

print(linalg.solve(matr_coef,b))

#Проверка решения через произведение

print(
np.allclose(
np.dot(matr_coef,linalg.solve(matr_coef,b)),b
))

[ 0.46666667  3.84444444 -5.55555556]
True


Константин, 
я еще попробовал выполнить решение с автоматизацией, чтобы коэффициенты при переменных системы уравнений вытаскивались не руками, но до конца не получилось. Если сможете направить, как надо действовать, буду признателен.

Поскольку инструментами для семантического анализа еще не владеем (чтобы понять, где при перменной коэффициент 0), то переписываем условие:
Решите систему уравнений:
4x + 2y + z = 4
x + 3y + 0z = 12
0x + 5y + 4z = -3

In [30]:
eq_syst='4x + 2y + z = 4 x + 3y + 0z = 12 0x + 5y + 4z = -3'
a1=[]
a2=[]
a3=[]

In [57]:
def make_line_matr(var, arr):
  arr=[]
  for i in range(len(eq_syst)): #Итерация по индексам, по элементам не работало - выводился первый коэфф, но несколько раз
    if eq_syst[i] == var:
      if eq_syst[i-1] ==' ':
        arr.append (1)
      else:
        arr.append (float( eq_syst[i-1] ))
  return arr

aa1=np.array([make_line_matr('x',a1)])
aa2=np.array([make_line_matr('y',a2)])
aa3=np.array([make_line_matr('z',a3)])
# В принципе, при большом числе переменных можно загнать создание строк коэффициентов в функцию, пробегая по списку с перменными

matr_coeff=np.concatenate((aa1,aa2,aa3))

matr_coeff


array([[4., 1., 0.],
       [2., 3., 5.],
       [1., 0., 4.]])

In [54]:
from numpy import linalg

print(linalg.solve(matr_coeff,b))

#Проверка решения через произведение

print(
np.allclose(
np.dot(matr_coeff,linalg.solve(matr_coeff,b)),b
))

[-0.33333333  5.33333333 -0.66666667]
True


Получается, у системы не одно решение.

In [ ]:
Не смог автоматизировать создание матрицы коэффициентов, то есть, сделать функцию для сборки массива коэффициентов 
в общую матрицу произвольного числа уравнений в системе. В варианте: 
matr=[]

for i in range (1,4):
  matr.append("aa{0}".format(i))

создается список  ['aa1', 'aa2', 'aa3'] Но как можно строковое значение 'aa1' конвертировать в переменную aa1 ?!

In [56]:
matr=[]

for i in range (1,4):
  matr.append("aa{0}".format(i))

print(matr)

['aa1', 'aa2', 'aa3']
